name: Deploy prod

on:
  workflow_dispatch:
  push:
    branches:
      - production

jobs:
  deploy:
    if: github.repository == 'fluid-project/lcil'

    runs-on: ubuntu-latest

    concurrency: deploy-prod

    steps:
      - name: Start deployment
        uses: bobheadxi/deployments@v0.6.0
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production

      - name: Deploy stack
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          proxy_host: ${{ secrets.SSH_PROXY_HOSTNAME }}
          proxy_username: ${{ secrets.SSH_PROXY_USERNAME }}
          proxy_key: ${{ secrets.SSH_PROXY_PRIVATE_KEY }}
          proxy_port: ${{ secrets.SSH_PROXY_PORT }}
          script: |
            cd /srv/fluid-lcil-prod && \
            git checkout -f && \
            git checkout production && \
            git pull && \
            ./bin/deploy-cloud.sh

      - name: Wait
        run: sleep 15

      - name: Smoke test
        run: curl --location --no-buffer --retry 120 --retry-delay 1 https://lcil-prod.fluidproject.org

      - name: Update deployment status
        uses: bobheadxi/deployments@v0.6.0
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://lcil-prod.fluidproject.org
